server:
  port: 8080
spring:
  #main:
  #web-application-type: reactive
  application:
    name: service-gateway
  cloud:
    # nacos配置
    nacos:
      discovery:
        server-addr: 192.168.17.130:8848
    gateway:
      discovery:
        locator:
          # 使用服务发现路由
          enabled: true
      routes:
        - id: service-sms  # 路由的id，没有固定规则但是要求唯一，建议和服务名一致
          uri: lb://service-sms  # 匹配后提供服务的路由地址
          predicates:
            - Path=/*/sms/**  # 断言，路径模式匹配
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/*/hosp/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**
        - id: service-doctor
          uri: lb://service-doctor
          predicates:
            - Path=/*/doctor/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**



