server:
  port: 8084
spring:
  application:
    name: service-sms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.17.130:3306/db_ghpt?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Mac010419..

  data:
    redis:
      host: 192.168.17.130
      port: 6379

  #rabbitmq地址
  rabbitmq:
    host: 192.168.17.130
    port: 5672
    username: guest
    password: guest

  # 配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.17.130:8848


aliyun:
  sms:
    regionId: cn-hangzhou
    accessKeyId: LTAI5tPe6Hne48BEdQrKJdK5
    accessKeySecret: CNPcpOxPWXawIDFyXGcfXvmowfyJgY
    signName: 智慧医疗项目
    templateCode: SMS_275235389